'use client';
import {useState} from 'react';
import {useAccount,useSignMessage} from 'wagmi';
import type {Address} from 'viem';
import {chatPromptHash,chatSignMessage} from '@/lib/agent-chat-auth';

type Line={role:'user'|'agent';text:string};
export function AgentChat({slug,name,active}:{slug:string;name:string;active:boolean;token:Address}){
  const {address,isConnected}=useAccount();const sign=useSignMessage();const [open,setOpen]=useState(false);const [message,setMessage]=useState('');const [lines,setLines]=useState<Line[]>([]);const [error,setError]=useState('');const [remaining,setRemaining]=useState<number|null>(null);const [busy,setBusy]=useState(false);
  async function send(){if(!address||!message.trim()||busy)return;setBusy(true);setError('');const clean=message.trim();try{const requestId=crypto.randomUUID(),issuedAt=new Date().toISOString();const statement=chatSignMessage({slug,address,messageHash:chatPromptHash(clean),requestId,issuedAt});const signature=await sign.signMessageAsync({message:statement});const response=await fetch(`/api/agents/${slug}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address,message:clean,requestId,issuedAt,signature})});const json=await response.json();if(!response.ok)throw new Error(json.error||'Chat failed.');setLines(v=>[...v,{role:'user',text:clean},{role:'agent',text:json.reply}]);setRemaining(json.remaining);setMessage('')}catch(e){setError(e instanceof Error?e.message:'Chat failed.')}finally{setBusy(false)}}
  return <><button type="button" onClick={()=>setOpen(v=>!v)} disabled={!active} className="fixed bottom-24 right-5 z-40 min-h-14 rounded-full bg-gradient-to-r from-cyan to-magenta px-5 font-black text-ink shadow-2xl disabled:cursor-not-allowed disabled:grayscale md:bottom-6">✦ {active?'Chat with agent':'Agent offline'}</button>{open&&<div className="fixed inset-x-3 bottom-40 z-40 ml-auto flex max-h-[70vh] max-w-md flex-col overflow-hidden rounded-3xl border border-white/10 bg-ink shadow-2xl md:bottom-24 md:right-6"><header className="border-b border-white/10 p-4"><b>Chat with {name}</b><p className="mt-1 text-xs text-muted">Holders only · minimum 0.1% supply · 10 messages/day</p></header><div className="min-h-48 flex-1 space-y-3 overflow-y-auto p-4">{lines.length===0&&<p className="text-sm text-muted">Sign one message with your connected wallet to prove token ownership. No gas is charged.</p>}{lines.map((line,i)=><div key={i} className={`rounded-2xl p-3 text-sm ${line.role==='user'?'ml-8 bg-cyan/10':'mr-8 bg-white/[.06]'}`}>{line.text}</div>)}</div><div className="border-t border-white/10 p-3">{error&&<p className="mb-2 text-xs text-red-300">{error}</p>}<div className="flex gap-2"><input className="input min-w-0" maxLength={600} placeholder={isConnected?'Ask something…':'Connect wallet first'} value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}}/><button className="btn btn-primary" disabled={!isConnected||busy||!message.trim()} onClick={()=>void send()}>{busy?'Signing…':'Send'}</button></div>{remaining!==null&&<p className="mt-2 text-right text-[11px] text-muted">{remaining} messages left today</p>}</div></div>}</>;
}
