'use client';

import Link from 'next/link';
import {useDeferredValue,useEffect,useState} from 'react';
import {keepPreviousData,useQuery} from '@tanstack/react-query';
import {OfficialTokenCard} from '@/components/official-token-card';
import {TokenImage} from '@/components/token-image';
import type {Launch,LaunchPage} from '@/lib/data';
import {usd,usdPrice} from '@/lib/swap';
import {short,shortB20} from '@/lib/utils';
import {Pagination} from '@/components/pagination';

type Metrics={totalLaunches:number;totalVolumeUsd:number|null;uniqueTraders:number;highestMarketCapUsd:number|null;highestMarketCapToken:string|null;highestMarketCapSymbol:string|null;updatedAt:string|null};
const number=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('en-US',{notation:value>=1000?'compact':'standard',maximumFractionDigits:1}).format(value);
const percent=(value:number|null|undefined)=>value==null?'—':`${value>=0?'+':''}${value.toFixed(2)}%`;
const age=(timestamp?:string)=>{if(!timestamp)return '—';const seconds=Math.max(0,Math.floor((Date.now()-new Date(timestamp).getTime())/1000));return seconds<3600?`${Math.max(1,Math.floor(seconds/60))}m`:seconds<86400?`${Math.floor(seconds/3600)}h`:`${Math.floor(seconds/86400)}d`};
const justLaunched=(timestamp?:string)=>!!timestamp&&Date.now()-new Date(timestamp).getTime()<30*60*1000;

function Empty(){return <div className="card col-span-full py-16 text-center"><svg className="mx-auto mb-5 h-28 w-28 text-magenta/70" viewBox="0 0 120 120" fill="none"><path d="M18 87c17-7 22-32 42-43 16-9 31-4 42 8" stroke="currentColor" strokeWidth="4"/><circle cx="69" cy="35" r="13" stroke="#40e8ff" strokeWidth="3"/><path d="m79 25 13-13M83 20l9 9" stroke="#40e8ff" strokeWidth="3"/><path d="M20 92c29-7 51 2 82-9" stroke="currentColor" strokeWidth="3"/></svg><h3 className="font-display text-xl font-bold">The lanterns are waiting</h3><p className="mt-2 text-muted">No launches were found in the current on-chain window.</p><Link href="/launch" className="btn btn-primary mt-6 inline-flex items-center">Launch the first token</Link></div>}

export function Discover({initialPage,metrics}:{initialPage:LaunchPage;metrics:Metrics}){
  const [mode,setMode]=useState<'grid'|'table'>('grid');const [q,setQ]=useState('');const [sort,setSort]=useState('new');const [page,setPage]=useState(1);const deferredQ=useDeferredValue(q);
  useEffect(()=>setPage(1),[deferredQ,sort]);
  const launches=useQuery<LaunchPage>({
    queryKey:['discover-launches',page,sort,deferredQ],
    initialData:page===1&&sort==='new'&&!deferredQ?initialPage:undefined,
    placeholderData:keepPreviousData,
    queryFn:async()=>{
      const params=new URLSearchParams({page:String(page),pageSize:'24',sort,q:deferredQ});
      const response=await fetch(`/api/tokens?${params}`);if(!response.ok)throw new Error('Launches unavailable');
      const data=await response.json() as Omit<LaunchPage,'items'>&{items:Array<Omit<Launch,'blockNumber'>&{blockNumber:string}>};
      return {...data,items:data.items.map(item=>({...item,blockNumber:BigInt(item.blockNumber)}))};
    },
  });
  const result=launches.data||initialPage,items=result.items;
  const go=(next:number)=>{setPage(next);document.getElementById('discover-launches')?.scrollIntoView({behavior:'smooth',block:'start'})};
  return <div>
    <section className="relative overflow-hidden px-4 pb-12 pt-12 sm:pb-14 sm:pt-16"><div aria-hidden className="pointer-events-none absolute right-[-8rem] top-[-10rem] h-96 w-96 rounded-full bg-cyan/10 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-9 lg:grid-cols-[minmax(0,3fr)_minmax(340px,2fr)] lg:gap-14"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.24em] text-cyan">B20 × VVV · Base</p><h1 className="max-w-3xl font-display text-5xl font-black leading-[.95] md:text-7xl">Launch into the<br/><span className="text-magenta">liquid night.</span></h1><p className="mt-6 max-w-xl text-lg text-muted">One launch. One locked v4 position. A market denominated entirely in VVV.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/launch" className="btn btn-primary inline-flex">Create a B20 <span className="ml-2">→</span></Link><a href="#discover-launches" className="btn btn-ghost inline-flex">Explore launches</a></div></div><OfficialTokenCard/></div></section>
    <section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto grid max-w-7xl grid-cols-2 px-4 md:grid-cols-4"><Stat label="Tokens launched" value={number(metrics.totalLaunches)} detail="Factory v1"/><Stat label="Total volume" value={usd(metrics.totalVolumeUsd)} detail="All-time indexed"/><Stat label="Unique traders" value={number(metrics.uniqueTraders)} detail="All-time wallets"/><Stat label="Highest market cap" value={usd(metrics.highestMarketCapUsd)} detail={metrics.highestMarketCapSymbol||'Current leader'}/></div></section>
    <section id="discover-launches" className="mx-auto max-w-7xl scroll-mt-24 px-4 py-12"><div className="mb-6 flex flex-col gap-3 md:flex-row"><input aria-label="Search launches" value={q} onChange={e=>setQ(e.target.value)} className="input flex-1" placeholder="Search name, symbol, or address"/><select className="input md:w-44" value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort"><option value="new">Newest</option><option value="volume">Volume</option><option value="mc">Market cap</option><option value="change">% change</option><option value="traders">Traders</option></select><div className="grid grid-cols-2 gap-1 rounded-xl border border-white/10 p-1"><button onClick={()=>setMode('grid')} className={`btn px-4 ${mode==='grid'?'bg-white/10 text-cyan':''}`} aria-label="Card grid">▦</button><button onClick={()=>setMode('table')} className={`btn px-4 ${mode==='table'?'bg-white/10 text-cyan':''}`} aria-label="Table">☷</button></div></div>{launches.isError?<div className="card p-8 text-center text-red-300">Launch data is temporarily unavailable.</div>:!items.length?<Empty/>:<div className={launches.isFetching?'opacity-60 transition-opacity':'transition-opacity'}>{mode==='grid'?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(x=><TokenCard key={x.token} x={x}/>)}</div>:<TokenTable items={items}/>}</div>}<Pagination page={result.page} totalPages={result.totalPages} totalItems={result.total} pageSize={result.pageSize} onPageChange={go} label="launches"/></section>
  </div>;
}

function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="min-w-0 border-white/10 px-3 py-5 even:border-l md:border-l md:px-5 md:first:border-l-0"><p className="truncate font-display text-xl font-black text-white sm:text-2xl" title={value}>{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 truncate text-[10px] text-cyan">{detail}</p></div>}
function TokenCard({x}:{x:Launch}){return <Link href={`/token/${x.token}`} className="card group p-5 transition hover:-translate-y-1 hover:border-magenta/50"><div className="flex items-center gap-3"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-magenta/30 to-cyan/20 text-xl font-black"><TokenImage src={x.image} alt={`${x.name} logo`} width={56} height={56} fallback={x.symbol||'?'}/></div><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate font-display text-lg font-bold">{x.name||'B20 Token'}</h3>{justLaunched(x.blockTimestamp)&&<span className="animate-pulse rounded-full bg-magenta/15 px-2 py-0.5 text-[9px] font-black text-magenta motion-reduce:animate-none">JUST LAUNCHED</span>}</div><p className="text-sm text-muted">{x.symbol||short(x.token)} · VVV</p></div><span className="ml-auto shrink-0 rounded-full border border-cyan/30 px-2 py-1 text-xs text-cyan">◆ Locked</span></div><div className="mt-7 grid grid-cols-2 gap-4"><Metric label="Price" value={usdPrice(x.priceUsd)} detail={x.priceVvv==null?'VVV unavailable':`${x.priceVvv.toPrecision(4)} VVV`}/><Metric label="Market cap" value={usd(x.marketCapUsd)} detail="1B fixed supply"/><Metric label="24h volume" value={usd(x.volume24hUsd)} detail={`${number(x.tx24h)} transactions`}/><Metric label="24h traders" value={number(x.traders24h)} detail={percent(x.change24h)}/></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs text-muted"><span className="font-mono" title={x.token}>{shortB20(x.token)}</span><span className="ml-2 shrink-0">{age(x.blockTimestamp)}</span></div></Link>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="min-w-0"><p className="text-xs text-muted">{label}</p><p className="mt-1 truncate font-semibold" title={value}>{value}</p><p className="mt-1 truncate text-[10px] text-muted">{detail}</p></div>}
function TokenTable({items}:{items:Launch[]}){return <div className="card overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted"><tr>{['Token','Price','MC','24h vol','24h','Traders','Tx','Age','LP'].map(h=><th className="px-4 py-4" key={h}>{h}</th>)}</tr></thead><tbody>{items.map(x=><tr className="border-t border-white/10 transition-colors hover:bg-white/[.025]" key={x.token}><td className="px-4 py-3"><Link href={`/token/${x.token}`} className="flex min-w-[180px] items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-xl border border-white/10 bg-gradient-to-br from-magenta/20 to-cyan/15 text-xs"><TokenImage src={x.image} alt={`${x.name} logo`} width={36} height={36} className="h-9 w-9 object-cover" fallback={x.symbol||'?'}/></span><span className="min-w-0"><b className="block max-w-[150px] truncate">{x.name||'B20 Token'}</b><span className="block max-w-[150px] truncate text-xs text-muted">{x.symbol||short(x.token)}</span></span></Link></td><td className="px-4">{usdPrice(x.priceUsd)}</td><td className="px-4">{usd(x.marketCapUsd)}</td><td className="px-4">{usd(x.volume24hUsd)}</td><td className={`px-4 ${x.change24h!=null&&x.change24h<0?'text-red-300':'text-emerald-300'}`}>{percent(x.change24h)}</td><td className="px-4">{number(x.traders24h)}</td><td className="px-4">{number(x.tx24h)}</td><td className="px-4 text-muted">{age(x.blockTimestamp)}</td><td className="px-4 text-cyan">Locked</td></tr>)}</tbody></table></div>}
