'use client';
import { useRef, useState } from 'react';
import { TokenImage } from '@/components/token-image';

export function ImageUpload({value,symbol,onChange}:{value:string;symbol:string;onChange:(url:string)=>void}) {
  const input=useRef<HTMLInputElement>(null); const [preview,setPreview]=useState(value); const [status,setStatus]=useState('');
  async function upload(file?:File){if(!file)return;if(!symbol.trim()){setStatus('Enter the token symbol before uploading.');return}if(!file.type.startsWith('image/')){setStatus('Choose an image file.');return}if(file.size>5_000_000){setStatus('Image must be under 5 MB.');return}const local=URL.createObjectURL(file);setPreview(local);setStatus('Uploading to IPFS…');const body=new FormData();body.append('file',file);body.append('symbol',symbol);try{const r=await fetch('/api/upload',{method:'POST',body});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');onChange(j.url);setPreview(j.url);setStatus(`Uploaded as ${j.fileName}.`)}catch(e){setStatus(e instanceof Error?e.message:'Upload failed. You can paste a public URL instead.')}}
  return <div><span className="mb-2 block text-sm text-muted">Token image</span><div className="flex items-center gap-4 rounded-2xl border border-dashed border-white/20 p-4"><div className="h-[72px] w-[72px] overflow-hidden rounded-2xl bg-white/5 text-2xl"><TokenImage src={preview} alt="Token preview" width={72} height={72} fallback="+"/></div><div><button type="button" onClick={()=>input.current?.click()} className="btn btn-ghost">Choose image</button><p className="mt-2 text-xs text-muted">Saved as SYMBOL.ext · max 5 MB</p></div><input ref={input} type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></div>{status&&<p className={`mt-2 text-sm ${status.startsWith('Uploaded')?'text-cyan':'text-muted'}`}>{status}</p>}<input value={value} onChange={e=>{onChange(e.target.value);setPreview(e.target.value)}} className="input mt-3" placeholder="Or paste an IPFS / public image URL"/></div>;
}
