'use client';
import {useInfiniteQuery,useQuery} from '@tanstack/react-query';
import {formatUnits,type Address} from 'viem';
import {short} from '@/lib/utils';
import {usd} from '@/lib/swap';

type Row={id:string;tx_hash:string;block_timestamp:string|null;sender:string|null;amount_in_raw:string;amount_out_raw:string;input_symbol:string;output_symbol:string;input_decimals:number;output_decimals:number;side:'buy'|'sell'};
type Response={rows:Row[];nextCursor:string|null;hasMore:boolean;indexedBlock:string|null;indexedAt:string|null;warning:string|null};
type Fx={prices:{VVV:number|null;ETH:number|null;USDC:number|null}};
const amount=(raw:string,decimals:number)=>Number(formatUnits(BigInt(raw),decimals));
const tokenAmount=(raw:string,decimals:number)=>{const value=amount(raw,decimals);if(!Number.isFinite(value))return '—';return value.toLocaleString('en-US',{notation:value>=1000?'compact':'standard',maximumFractionDigits:value<1?6:3})};
const age=(timestamp:string|null)=>{if(!timestamp)return '—';const seconds=Math.max(0,Math.floor((Date.now()-new Date(timestamp).getTime())/1000));return seconds<60?`${seconds}s`:seconds<3600?`${Math.floor(seconds/60)}m`:seconds<86400?`${Math.floor(seconds/3600)}h`:`${Math.floor(seconds/86400)}d`};

export function LatestSwaps({token,symbol}:{token:Address;symbol:string}){
  const swaps=useInfiniteQuery<Response>({queryKey:['latest-swaps',token],initialPageParam:null as string|null,queryFn:async({pageParam})=>{const pageCursor=typeof pageParam==='string'?pageParam:null;const cursor=pageCursor?`&cursor=${encodeURIComponent(pageCursor)}`:'';const response=await fetch(`/api/swaps?token=${token}${cursor}`);if(!response.ok)throw new Error('Latest swaps are temporarily unavailable.');return response.json()},getNextPageParam:last=>last.nextCursor||undefined,refetchInterval:()=>typeof document!=='undefined'&&document.hidden?false:20_000,staleTime:10_000});
  const fx=useQuery<Fx>({queryKey:['asset-fx'],queryFn:async()=>fetch('/api/fx').then(response=>response.json()),staleTime:30_000});
  const rows=swaps.data?.pages.flatMap(page=>page.rows)||[];const latest=swaps.data?.pages[0];
  const assetName=(value:string)=>value==='B20'?symbol:value;
  const valueUsd=(row:Row)=>{const externalSymbol=row.side==='buy'?row.input_symbol:row.output_symbol;const raw=row.side==='buy'?row.amount_in_raw:row.amount_out_raw;const decimals=row.side==='buy'?row.input_decimals:row.output_decimals;const price=fx.data?.prices?.[externalSymbol as keyof Fx['prices']];return price==null?null:amount(raw,decimals)*price};
  return <section className="card overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-white/10 p-5 sm:p-6"><div><div className="flex items-center gap-2"><h2 className="font-display text-xl font-bold">Latest swaps</h2><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-2 py-0.5 text-[10px] font-bold text-emerald-300">● LIVE</span></div><p className="mt-1 text-xs text-muted">LiqpadSwapRouter · up to 20 confirmed swaps</p></div><button aria-label="Refresh latest swaps" disabled={swaps.isFetching} onClick={()=>swaps.refetch()} className="btn btn-ghost min-h-11 px-3">{swaps.isFetching?'…':'↻'}</button></div>
    {swaps.isLoading?<SwapSkeleton/>:swaps.isError?<div className="p-8 text-center"><p className="text-red-300">Latest swaps are temporarily unavailable.</p><button onClick={()=>swaps.refetch()} className="btn btn-ghost mt-4">Try again</button></div>:!rows.length?<div className="p-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full border border-cyan/20 bg-cyan/[.06] text-2xl text-cyan">↕</div><p className="mt-4 font-bold">No indexed swaps yet</p><p className="mt-2 text-sm text-muted">Trading activity may still be syncing from Base.</p></div>:<><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-muted"><tr>{['Type','Trader','Paid','Received','Value','Time','Tx'].map(label=><th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/10"><td className="px-4 py-4"><Side side={row.side}/></td><td className="px-4 font-mono text-xs">{row.sender?short(row.sender):'—'}</td><td className="px-4 font-medium">{tokenAmount(row.amount_in_raw,row.input_decimals)} {assetName(row.input_symbol)}</td><td className="px-4 font-medium">{tokenAmount(row.amount_out_raw,row.output_decimals)} {assetName(row.output_symbol)}</td><td className="px-4 text-muted">{usd(valueUsd(row))}</td><td className="px-4 text-muted">{age(row.block_timestamp)}</td><td className="px-4"><a href={`https://basescan.org/tx/${row.tx_hash}`} target="_blank" rel="noreferrer" aria-label="View transaction on BaseScan" className="text-cyan">↗</a></td></tr>)}</tbody></table></div><div className="divide-y divide-white/10 md:hidden">{rows.map(row=><article key={row.id} className={`border-l-2 p-4 ${row.side==='buy'?'border-cyan':'border-magenta'}`}><div className="flex items-center justify-between"><Side side={row.side}/><span className="text-xs text-muted">{age(row.block_timestamp)}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-[10px] uppercase tracking-wider text-muted">Paid</p><p className="mt-1 text-sm font-bold">{tokenAmount(row.amount_in_raw,row.input_decimals)} {assetName(row.input_symbol)}</p></div><div><p className="text-[10px] uppercase tracking-wider text-muted">Received</p><p className="mt-1 text-sm font-bold">{tokenAmount(row.amount_out_raw,row.output_decimals)} {assetName(row.output_symbol)}</p></div></div><p className="mt-2 text-xs text-muted">{usd(valueUsd(row))}</p><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-3 text-xs"><span className="font-mono text-muted">{row.sender?short(row.sender):'—'}</span><a href={`https://basescan.org/tx/${row.tx_hash}`} target="_blank" rel="noreferrer" className="text-cyan">Transaction ↗</a></div></article>)}</div></>}
    {swaps.hasNextPage&&<div className="border-t border-white/10 p-4"><button disabled={swaps.isFetchingNextPage} onClick={()=>swaps.fetchNextPage()} className="btn btn-ghost w-full">{swaps.isFetchingNextPage?'Loading…':'Load older swaps'}</button></div>}
    {latest?.warning&&<p className="border-t border-amber-400/20 bg-amber-400/[.06] px-5 py-3 text-xs text-amber-200">{latest.warning}</p>}
  </section>
}
function Side({side}:{side:'buy'|'sell'}){return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-black ${side==='buy'?'border-cyan/30 bg-cyan/10 text-cyan':'border-magenta/30 bg-magenta/10 text-magenta'}`}>{side.toUpperCase()}</span>}
function SwapSkeleton(){return <div role="status" aria-label="Loading latest swaps" className="animate-pulse divide-y divide-white/10 motion-reduce:animate-none">{Array.from({length:4},(_,i)=><div key={i} className="flex gap-4 p-4"><div className="h-7 w-14 rounded-full bg-white/10"/><div className="h-5 flex-1 rounded bg-white/[.06]"/><div className="h-5 w-24 rounded bg-white/[.06]"/></div>)}<span className="sr-only">Loading latest swaps…</span></div>}
