'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {getAddress,zeroAddress,zeroHash,type Hex} from 'viem';
import {useAccount,useChainId,useSimulateContract,useSwitchChain,useWaitForTransactionReceipt,useWriteContract} from 'wagmi';
import {useRouter} from 'next/navigation';
import {ADDRESSES,CHAIN_ID} from '@/lib/constants';
import {isQuoteExpired,type SignedLaunchQuote} from '@/lib/launch-quote';
import {useAutoMineB07} from '@/hooks/useAutoMineB07';
import {hasB07Suffix} from '@/lib/suffix';
import {factoryAbi} from '@/src/abi/factory';
import {ImageUpload} from '@/components/image-upload';
import {LaunchPreview} from '@/components/launch-preview';
import {LaunchTransactionOverlay} from '@/components/launch-transaction-overlay';
import {short} from '@/lib/data';

type Form={name:string;symbol:string;image:string;description:string;website:string;twitter:string;telegram:string;farcaster:string;discord:string;targetFdv:string};
const blank:Form={name:'',symbol:'',image:'',description:'',website:'',twitter:'',telegram:'',farcaster:'',discord:'',targetFdv:'10000'};

export function LaunchWizard(){
  const [step,setStep]=useState(1);const [form,setForm]=useState(blank);const [salt,setSalt]=useState<Hex>();const [quote,setQuote]=useState<SignedLaunchQuote>();
  const [quoteStatus,setQuoteStatus]=useState<'idle'|'loading'|'ready'|'error'>('idle');const [quoteError,setQuoteError]=useState('');const [now,setNow]=useState(()=>Math.floor(Date.now()/1000));
  const [contractURI,setContractURI]=useState('');const [metadataURL,setMetadataURL]=useState('');const [metadataStatus,setMetadataStatus]=useState<'idle'|'uploading'|'ready'|'error'>('idle');const [metadataError,setMetadataError]=useState('');
  const [indexStatus,setIndexStatus]=useState<'idle'|'confirming'|'saved'|'error'>('idle');const [indexError,setIndexError]=useState('');const [launchedToken,setLaunchedToken]=useState<string>();
  const confirmedHash=useRef<string|undefined>(undefined);const router=useRouter();const {address,isConnected}=useAccount();const chainId=useChainId();const switchChain=useSwitchChain();
  const miner=useAutoMineB07();
  useEffect(()=>{const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),1000);return()=>clearInterval(timer)},[]);
  const quoteExpired=!quote||isQuoteExpired(quote.quote.validUntil,now);const expiry=quote?Math.max(0,Number(BigInt(quote.quote.validUntil)-BigInt(now))):0;
  const launchParams=useMemo(()=>({name:form.name,symbol:form.symbol,salt:salt||zeroHash,contractURI,description:form.description,logoURI:form.image,website:form.website,socials:{twitter:form.twitter,telegram:form.telegram,farcaster:form.farcaster,discord:form.discord},creator:address||zeroAddress}),[address,contractURI,form,salt]);
  const launchQuote=useMemo(()=>quote?{...quote.quote,validUntil:BigInt(quote.quote.validUntil)}:{quotedFrame:0,validUntil:0n,creator:address||zeroAddress,launchSalt:salt||zeroHash},[address,quote,salt]);
  const args=useMemo(()=>[launchParams,launchQuote,quote?.signature||'0x'] as const,[launchParams,launchQuote,quote]);
  const canSimulate=isConnected&&chainId===CHAIN_ID&&step===4&&!!salt&&!!address&&metadataStatus==='ready'&&!!contractURI&&!!quote?.signature&&!quoteExpired;
  const sim=useSimulateContract({address:ADDRESSES.factory,abi:factoryAbi,functionName:'createLaunch',args,account:address,query:{enabled:canSimulate}});const write=useWriteContract();
  const receipt=useWaitForTransactionReceipt({hash:write.data,confirmations:1,query:{enabled:!!write.data}});
  const confirmDatabase=useCallback(async(hash:Hex)=>{confirmedHash.current=hash;setIndexStatus('confirming');setIndexError('');try{const response=await fetch('/api/launch/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({hash,expectedToken:quote?.predictedToken})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Database confirmation failed.');if(quote&&getAddress(result.token)!==getAddress(quote.predictedToken))throw new Error('Created token does not match signed prediction.');setLaunchedToken(result.token);setIndexStatus('saved');router.refresh();window.setTimeout(()=>router.push(`/token/${result.token}`),900)}catch(error){confirmedHash.current=undefined;setIndexStatus('error');setIndexError(error instanceof Error?error.message:'Database confirmation failed.')}},[quote,router]);
  useEffect(()=>{if(!write.data||!receipt.isSuccess||confirmedHash.current===write.data)return;void confirmDatabase(write.data)},[confirmDatabase,receipt.isSuccess,write.data]);
  const invalidate=useCallback(()=>{setContractURI('');setMetadataURL('');setMetadataStatus('idle');setQuote(undefined);setQuoteStatus('idle');setSalt(undefined)},[]);
  const updateForm=useCallback((key:keyof Form,value:string)=>{setForm(current=>({...current,[key]:value}));invalidate()},[invalidate]);
  async function requestQuote(nextSalt:Hex){if(!address)throw new Error('Connect your wallet first.');setQuoteStatus('loading');setQuoteError('');const response=await fetch('/api/launch/quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creator:address,launchSalt:nextSalt,targetFdvUsd:Number(form.targetFdv)})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Signed quote unavailable.');if(!miner.result||getAddress(result.predictedToken)!==getAddress(miner.result.token)||!hasB07Suffix(result.predictedToken))throw new Error('Signed prediction does not match the verified 0xb07 address.');setQuote(result);setQuoteStatus('ready')}
  async function prepareLaunch(){setMetadataStatus('uploading');setMetadataError('');try{if(chainId!==CHAIN_ID)throw new Error('Switch your wallet to Base mainnet.');const candidate=await miner.verify();const response=await fetch('/api/upload/metadata',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Metadata upload failed.');setContractURI(result.uri);setMetadataURL(result.url);setMetadataStatus('ready');setSalt(candidate.salt);await requestQuote(candidate.salt);setStep(4)}catch(error){setMetadataStatus('error');setQuoteStatus('error');const message=error instanceof Error?error.message:'Launch preparation failed.';setMetadataError(message);setQuoteError(message)}}
  async function refreshQuote(){if(!salt)return;try{await requestQuote(salt)}catch(error){setQuoteStatus('error');setQuoteError(error instanceof Error?error.message:'Signed quote unavailable.')}}
  const field=(key:keyof Form,label:string,placeholder='',area=false)=>{const Input=area?'textarea':'input';return <label className="block"><span className="mb-2 block text-sm text-muted">{label}</span><Input value={form[key]} onChange={e=>updateForm(key,e.target.value)} className="input" placeholder={placeholder}/></label>};
  const transactionActive=write.isPending||receipt.isLoading||indexStatus==='confirming'||indexStatus==='saved';const overlayPhase=write.isPending?'wallet':receipt.isLoading?'confirming':receipt.isSuccess&&indexStatus==='idle'?'database':indexStatus==='confirming'?'database':indexStatus==='saved'?'success':receipt.isError||indexStatus==='error'?'error':undefined;
  const launchLabel=!isConnected?'Connect wallet to continue':chainId!==CHAIN_ID?'Switch to Base':quoteStatus==='loading'?'Signing launch quote…':quoteExpired?'Refresh expired quote':sim.isLoading?'Simulating…':'Create launch';
  function launch(){if(chainId!==CHAIN_ID){switchChain.switchChain({chainId:CHAIN_ID});return}if(quoteExpired){void refreshQuote();return}if(sim.data?.request)write.writeContract(sim.data.request)}
  return <div className="mx-auto max-w-7xl px-4 py-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan">Launcher v1 · {step}/4</p><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><h1 className="font-display text-4xl font-black">Create a B20</h1><div className={`rounded-full border px-3 py-2 text-xs ${miner.status==='verified'?'border-cyan/30 bg-cyan/10 text-cyan':'border-white/10 text-muted'}`}>{miner.status==='verified'?'Liqpad 0xb07 address ready ✓':miner.status==='verifying'?'Verifying branded address…':`Preparing 0xb07 address… ${miner.rate?`${miner.rate.toLocaleString()}/s`:''}`}</div></div><div className="mt-8 flex gap-2">{[1,2,3,4].map(n=><div key={n} className={`h-1 flex-1 rounded ${n<=step?'bg-magenta':'bg-white/10'}`}/>)}</div><div className="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><fieldset disabled={transactionActive} className="card p-5 disabled:cursor-wait disabled:opacity-60 md:p-8">
  {step===1&&<div className="space-y-5"><h2 className="font-display text-2xl font-bold">Identity</h2>{field('name','Name','Night Bloom')}{field('symbol','Symbol','BLOOM')}<ImageUpload value={form.image} symbol={form.symbol} onChange={image=>updateForm('image',image)}/></div>}
  {step===2&&<div className="space-y-5"><h2 className="font-display text-2xl font-bold">Story & links</h2>{field('description','Description','Tell the market what blooms after dark.',true)}<details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-bold">Socials & links <span className="font-normal text-muted">(optional)</span></summary><div className="mt-5 space-y-5">{field('website','Website','https://liqpad.com')}{field('twitter','Twitter / X','https://x.com/…')}{field('telegram','Telegram')}{field('farcaster','Farcaster')}{field('discord','Discord')}</div></details></div>}
  {step===3&&<div className="space-y-5"><h2 className="font-display text-2xl font-bold">Opening target</h2>{field('targetFdv','Target opening FDV (USD)','$10,000')}<div className="divide-y divide-white/10">{[['Supply','1,000,000,000 B20'],['Pool','B20 · VVV'],['Pool fee','0'],['Initial VVV','0'],['Liquidity','Single-sided B20'],['LP','Permanently locked']].map(([k,v])=><div className="flex justify-between gap-4 py-4" key={k}><span className="text-muted">{k}</span><b className="text-right">{v}</b></div>)}</div></div>}
  {step===4&&<div><h2 className="font-display text-2xl font-bold">Signed launch review</h2>{metadataURL&&<a href={metadataURL} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm text-cyan">View contract metadata ↗</a>}{quote&&<div className="mt-5 divide-y divide-white/10">{[['Creator',short(quote.quote.creator)],['Branded B20 address',quote.predictedToken],['Address suffix','0xb07 ✓'],['Target FDV',`$${Number(form.targetFdv).toLocaleString()}`],['VVV reference',`$${quote.vvvUsd.toLocaleString(undefined,{maximumSignificantDigits:6})}`],['Estimated FDV',`$${quote.estimatedOpeningFDV.toLocaleString(undefined,{maximumFractionDigits:0})}`],['Signed frame',String(quote.quote.quotedFrame)],['Pool tick',String(quote.poolTick)],['Tick range',`${quote.tickLower} → ${quote.tickUpper}`],['Quote expires',`${expiry}s`],['Contract URI',contractURI]].map(([k,v])=><div className="flex justify-between gap-4 py-3 text-sm" key={k}><span className="text-muted">{k}</span><b className="max-w-[65%] break-all text-right">{v}</b></div>)}</div>}{quoteStatus==='loading'&&<p className="mt-5 text-cyan">Requesting secure launch signature…</p>}{quoteError&&<p className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{quoteError}</p>}{sim.error&&<p className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">Simulation unavailable: {sim.error.message}</p>}<button disabled={transactionActive||(!quoteExpired&&!sim.data?.request)||quoteStatus==='loading'} onClick={launch} className="btn btn-primary mt-6 w-full disabled:opacity-40">{launchLabel}</button></div>}
  {metadataError&&<p className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{metadataError}</p>}{miner.error&&<div className="mt-3 flex items-center gap-3 text-xs text-amber-200"><span>{miner.error}</span><button type="button" onClick={miner.restart} className="min-h-11 rounded-lg border border-amber-200/30 px-3 font-bold">Try again</button></div>}<div className="mt-8 flex justify-between"><button disabled={step===1||metadataStatus==='uploading'} onClick={()=>setStep(s=>s-1)} className="btn btn-ghost disabled:opacity-0">Back</button>{step<3&&<button disabled={(step===1&&(!form.name.trim()||!form.symbol.trim()||!form.image.trim()))||(step===2&&!form.description.trim())} onClick={()=>setStep(s=>s+1)} className="btn btn-primary disabled:opacity-40">Continue</button>}{step===3&&<button disabled={metadataStatus==='uploading'||!isConnected||!Number(form.targetFdv)||miner.status!=='verified'} onClick={prepareLaunch} className="btn btn-primary disabled:opacity-40">{metadataStatus==='uploading'?'Preparing signed launch…':miner.status!=='verified'?'Preparing branded address…':'Prepare launch'}</button>}</div></fieldset><LaunchPreview name={form.name} symbol={form.symbol} image={form.image} description={form.description} website={form.website}/></div>{overlayPhase&&<LaunchTransactionOverlay phase={overlayPhase} hash={write.data} token={launchedToken||quote?.predictedToken} error={receipt.error?.message||indexError} onRetry={indexStatus==='error'&&write.data?()=>void confirmDatabase(write.data as Hex):undefined}/>}</div>;
}
