const Pulse=({className}:{className:string})=><div aria-hidden className={`rounded-xl bg-white/[.07] ${className}`}/>;
const Card=({className='',children}:{className?:string;children?:React.ReactNode})=><div aria-hidden className={`card bg-white/[.015] ${className}`}>{children}</div>;

export function DiscoverSkeleton(){return <SkeletonFrame label="Loading Discover"><section className="px-4 pb-12 pt-12 sm:pt-16"><div className="mx-auto grid max-w-7xl items-center gap-9 lg:grid-cols-[minmax(0,3fr)_minmax(340px,2fr)] lg:gap-14"><div><Pulse className="h-4 w-36"/><Pulse className="mt-5 h-14 w-full max-w-2xl sm:h-20"/><Pulse className="mt-3 h-14 w-4/5 max-w-xl sm:h-20"/><Pulse className="mt-7 h-6 w-full max-w-lg"/><div className="mt-8 flex gap-3"><Pulse className="h-12 w-40"/><Pulse className="h-12 w-36"/></div></div><Card className="h-[360px] rounded-[1.75rem]"/></div></section><div className="border-y border-white/10 bg-white/[.02]"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-4 py-5 md:grid-cols-3">{Array.from({length:3},(_,i)=><Pulse key={i} className={`h-12 ${i===2?'hidden md:block':''}`}/>)}</div></div><section className="mx-auto max-w-7xl px-4 py-12"><div className="flex flex-col gap-3 md:flex-row"><Pulse className="h-12 flex-1"/><Pulse className="h-12 w-full md:w-44"/><Pulse className="h-12 w-full md:w-24"/></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6},(_,i)=><Card key={i} className="h-56"/>)}</div></section></SkeletonFrame>}

export function LaunchSkeleton(){return <SkeletonFrame label="Loading Launch"><div className="mx-auto max-w-7xl px-4 py-12"><Pulse className="h-4 w-32"/><div className="mt-4 flex items-center justify-between gap-5"><Pulse className="h-11 w-64"/><Pulse className="h-9 w-56 rounded-full"/></div><div className="mt-8 grid grid-cols-4 gap-2">{Array.from({length:4},(_,i)=><Pulse key={i} className="h-1"/>)}</div><div className="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><Card className="min-h-[540px] p-6"><Pulse className="h-8 w-32"/><Pulse className="mt-8 h-4 w-20"/><Pulse className="mt-2 h-12 w-full"/><Pulse className="mt-6 h-4 w-20"/><Pulse className="mt-2 h-12 w-full"/><Pulse className="mt-6 h-44 w-full"/><div className="mt-8 flex justify-end"><Pulse className="h-12 w-32"/></div></Card><Card className="h-[430px] lg:sticky lg:top-24"/></div></div></SkeletonFrame>}

export function TokenSkeleton(){return <SkeletonFrame label="Loading token details"><div className="mx-auto max-w-7xl px-4 py-10"><div className="flex items-center gap-5"><Pulse className="h-24 w-24 rounded-3xl"/><div className="flex-1"><Pulse className="h-10 w-64"/><Pulse className="mt-3 h-5 w-80 max-w-full"/></div></div><div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({length:4},(_,i)=><Card key={i} className="h-28"/>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-6"><Card className="h-[420px] sm:h-[520px]"/><Card className="h-56"/></div><div className="space-y-4"><Card className="h-[430px]"/><Card className="h-36"/></div></div></div></SkeletonFrame>}

export function CreatorSkeleton(){return <SkeletonFrame label="Loading creator"><div className="mx-auto max-w-5xl px-4 py-12"><div className="flex items-center gap-4"><Pulse className="h-20 w-20 rounded-full"/><div><Pulse className="h-4 w-20"/><Pulse className="mt-3 h-9 w-56"/></div></div><div className="mt-8 grid gap-4 md:grid-cols-3">{Array.from({length:3},(_,i)=><Card key={i} className="h-32"/>)}</div><Pulse className="mt-12 h-8 w-32"/><div className="mt-4 space-y-3">{Array.from({length:4},(_,i)=><Card key={i} className="h-16"/>)}</div></div></SkeletonFrame>}

export function MeSkeleton(){return <SkeletonFrame label="Loading wallet dashboard"><div className="mx-auto max-w-5xl px-4 py-12"><Pulse className="h-4 w-32"/><Pulse className="mt-3 h-11 w-64"/><div className="mt-8 grid gap-4 md:grid-cols-2"><Card className="h-40"/><Card className="h-40"/></div><Pulse className="mt-10 h-8 w-44"/><div className="mt-4 space-y-3">{Array.from({length:3},(_,i)=><Card key={i} className="h-16"/>)}</div></div></SkeletonFrame>}

export function DocsSkeleton(){return <SkeletonFrame label="Loading documentation"><article className="mx-auto max-w-3xl px-4 py-14"><Pulse className="h-4 w-36"/><Pulse className="mt-5 h-14 w-full"/><Pulse className="mt-3 h-14 w-4/5"/><div className="mt-8 space-y-3"><Pulse className="h-5 w-full"/><Pulse className="h-5 w-full"/><Pulse className="h-5 w-3/4"/></div><Card className="my-9 h-48"/><Pulse className="h-9 w-48"/><div className="mt-5 space-y-3">{Array.from({length:5},(_,i)=><Card key={i} className="h-14"/>)}</div></article></SkeletonFrame>}

function SkeletonFrame({label,children}:{label:string;children:React.ReactNode}){return <div role="status" aria-live="polite" aria-label={label} className="animate-pulse motion-reduce:animate-none">{children}<span className="sr-only">{label}…</span></div>}
