'use client';

import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {formatUnits} from 'viem';
import {usd} from '@/lib/swap';

type Point={date:string;fees:string;swept:string;staked:string;svvvLocked:string;diemMinted:string;diemStaked:string};
type ChartData={series:Point[];price:{usd:number;source:string;timestamp:number}|null;truncated:boolean};
type Range='7D'|'30D'|'ALL';type Mode='TOKEN'|'USD';type Key='fees'|'swept'|'staked';
const lines:{key:Key;label:string;color:string}[]=[{key:'fees',label:'Fees accrued',color:'#40e8ff'},{key:'swept',label:'VVV swept',color:'#ff3aa7'},{key:'staked',label:'VVV staked',color:'#9b7bff'}];
const amount=(raw:string)=>Number(formatUnits(BigInt(raw),18));

export function ProtocolGrowthChart(){
  const [range,setRange]=useState<Range>('30D');const [mode,setMode]=useState<Mode>('TOKEN');
  const query=useQuery<ChartData>({queryKey:['protocol-chart'],queryFn:async()=>{const response=await fetch('/api/transparency/chart');if(!response.ok)throw new Error('Chart data unavailable');return response.json()},staleTime:30_000,refetchInterval:60_000,retry:1});
  const points=useMemo(()=>{const all=query.data?.series||[];if(range==='ALL'||!all.length)return all;const end=new Date(`${all.at(-1)!.date}T00:00:00Z`).getTime();const days=range==='7D'?7:30;return all.filter(point=>new Date(`${point.date}T00:00:00Z`).getTime()>=end-(days-1)*86_400_000)},[query.data,range]);
  const price=query.data?.price?.usd??null;const factor=mode==='USD'?(price||0):1;const values=points.flatMap(point=>lines.map(line=>amount(point[line.key])*factor));const max=Math.max(...values,1);const width=900,height=300,pad=34;const x=(index:number)=>points.length<=1?width/2:pad+index*(width-pad*2)/(points.length-1);const y=(value:number)=>height-pad-(value/max)*(height-pad*2);const path=(key:Key)=>points.map((point,index)=>`${index?'L':'M'} ${x(index).toFixed(1)} ${y(amount(point[key])*factor).toFixed(1)}`).join(' ');
  return <section className="mt-12"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-2xl font-bold sm:text-3xl">Protocol growth</h2><p className="mt-1 text-sm text-muted">Cumulative confirmed VVV flows from indexed Base events.</p></div><div className="flex flex-wrap gap-2"><Toggle values={['7D','30D','ALL']} value={range} set={value=>setRange(value as Range)}/><Toggle values={['TOKEN','USD']} value={mode} set={value=>setMode(value as Mode)} disabled={mode==='TOKEN'&&price==null}/></div></div><div className="card min-w-0 overflow-hidden p-4 sm:p-6">{query.isLoading?<div className="h-72 animate-pulse rounded-xl bg-white/[.04]"/>:query.isError||!points.length?<div className="grid h-72 place-items-center text-center text-sm text-muted">No indexed Sweep or Harvest history is available yet.</div>:<><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs">{lines.map(line=><span key={line.key} className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{background:line.color}}/>{line.label}</span>)}</div><div className="mt-4 w-full overflow-hidden"><svg role="img" aria-label="Cumulative protocol VVV chart" viewBox={`0 0 ${width} ${height}`} className="h-auto min-h-56 w-full" preserveAspectRatio="none"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="rgba(255,255,255,.12)"/><line x1={pad} y1={pad} x2={pad} y2={height-pad} stroke="rgba(255,255,255,.12)"/>{lines.map(line=><path key={line.key} d={path(line.key)} fill="none" stroke={line.color} strokeWidth="4" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/>)}{points.length===1&&lines.map(line=><circle key={line.key} cx={x(0)} cy={y(amount(points[0][line.key])*factor)} r="6" fill={line.color}/>)}</svg></div><div className="mt-3 flex items-start justify-between gap-4 text-xs text-muted"><span>{points[0].date}</span><span className="text-right">{points.at(-1)!.date}<br/>{mode==='USD'?'USD estimate at the current VVV price':'Native token units'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{lines.map(line=>{const value=amount(points.at(-1)![line.key]);return <div key={line.key} className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs text-muted">{line.label}</p><p className="mt-1 font-bold">{mode==='USD'?usd(price==null?null:value*price):`${value.toLocaleString('en-US',{maximumFractionDigits:4})} VVV`}</p></div>})}</div>{query.data?.truncated&&<p className="mt-4 text-xs text-amber-200">The 5,000-event chart limit was reached. Run archival aggregation before treating this as complete lifetime history.</p>}</>}</div></section>;
}

function Toggle({values,value,set,disabled=false}:{values:string[];value:string;set:(value:string)=>void;disabled?:boolean}){return <div className="flex rounded-xl border border-white/10 bg-black/20 p-1">{values.map(item=><button key={item} type="button" disabled={disabled&&item==='USD'} onClick={()=>set(item)} className={`min-h-9 rounded-lg px-3 text-xs font-bold transition ${value===item?'bg-white/10 text-white':'text-muted hover:text-white'} disabled:opacity-40`}>{item}</button>)}</div>}
