'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {formatUnits,type Address} from 'viem';
import {useAccount,useBalance,useChainId,usePublicClient,useReadContract,useSwitchChain,useWaitForTransactionReceipt,useWriteContract} from 'wagmi';
import {chain} from '@/lib/chain';import {ADDRESSES} from '@/lib/constants';
import {applySlippage,assetDecimals,compactToken,parseAmount,type RouteAsset,type SwapSide,usd} from '@/lib/swap';
import {useSwapQuote} from '@/hooks/useSwapQuote';import {erc20Abi} from '@/src/abi/swapSupport';import {swapRouterAbi} from '@/src/abi/swapRouter';import {SwapTransactionOverlay} from '@/components/swap-transaction-overlay';

const ETH_GAS_RESERVE=100_000_000_000_000n;
export function SwapWidget({token,symbol}:{token:Address;symbol:string}){
  const queryClient=useQueryClient();
  const [side,setSide]=useState<SwapSide>('buy');const [asset,setAsset]=useState<RouteAsset>('ETH');const [input,setInput]=useState('');const [slippage,setSlippage]=useState(0.5);const [deadlineMinutes,setDeadlineMinutes]=useState(20);const [simulating,setSimulating]=useState(false);const [autoSwap,setAutoSwap]=useState(false);const [continueReady,setContinueReady]=useState(false);const [localError,setLocalError]=useState('');const handledApproval=useRef<string|undefined>(undefined);
  const {address,isConnected}=useAccount();const chainId=useChainId();const switchChain=useSwitchChain();const client=usePublicClient();
  const inputAsset=side==='buy'?asset:'VVV';const amountIn=useMemo(()=>parseAmount(input,inputAsset),[input,inputAsset]);const slippageBps=Math.max(1,Math.min(2000,Math.round(slippage*100)));
  const nativeBalance=useBalance({address,query:{enabled:!!address}});const usdcBalance=useReadContract({address:ADDRESSES.usdc,abi:erc20Abi,functionName:'balanceOf',args:[address!],query:{enabled:!!address}});const vvvBalance=useReadContract({address:ADDRESSES.vvv,abi:erc20Abi,functionName:'balanceOf',args:[address!],query:{enabled:!!address}});const b20Balance=useReadContract({address:token,abi:erc20Abi,functionName:'balanceOf',args:[address!],query:{enabled:!!address}});
  const approvalToken=side==='sell'?token:asset==='USDC'?ADDRESSES.usdc:asset==='VVV'?ADDRESSES.vvv:undefined;
  const allowance=useReadContract({address:approvalToken||ADDRESSES.vvv,abi:erc20Abi,functionName:'allowance',args:[address!,ADDRESSES.swapRouter],query:{enabled:!!address&&!!approvalToken}});
  const validToken=useReadContract({address:ADDRESSES.factory,abi:[{type:'function',name:'isLiqpadLaunch',stateMutability:'view',inputs:[{name:'token',type:'address'}],outputs:[{type:'bool'}]}] as const,functionName:'isLiqpadLaunch',args:[token]});
  const quote=useSwapQuote(token,asset,side,amountIn);const currentQuote=quote.data?.amountIn===amountIn&&Date.now()-quote.data.quotedAt<30_000?quote.data:undefined;
  const fx=useQuery({queryKey:['asset-fx'],queryFn:async()=>{const response=await fetch('/api/fx');if(!response.ok)throw new Error('FX unavailable');return response.json() as Promise<{prices:{ETH:number|null;USDC:number|null;VVV:number|null}}>},staleTime:30_000,retry:1});
  const balance=side==='sell'?(b20Balance.data||0n):asset==='ETH'?(nativeBalance.data?.value||0n):asset==='USDC'?(usdcBalance.data||0n):(vvvBalance.data||0n);const balanceDecimals=side==='buy'?assetDecimals(asset):18;
  const minimumOut=currentQuote?applySlippage(currentQuote.output,slippageBps):0n;const needsApproval=!!approvalToken&&amountIn>0n&&(allowance.data||0n)<amountIn;
  const approve=useWriteContract();const swap=useWriteContract();const approveReceipt=useWaitForTransactionReceipt({hash:approve.data,query:{enabled:!!approve.data}});const swapReceipt=useWaitForTransactionReceipt({hash:swap.data,query:{enabled:!!swap.data}});
  // The confirmed approval hash is the state-machine trigger; the ref guard prevents duplicate wallet requests.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!approveReceipt.isSuccess||!approve.data||handledApproval.current===approve.data)return;handledApproval.current=approve.data;void(async()=>{setAutoSwap(true);setContinueReady(false);setLocalError('');await allowance.refetch();const fresh=await quote.refetch();approve.reset();if(!fresh.data||fresh.data.amountIn!==amountIn){setLocalError('Approval succeeded, but the refreshed quote is unavailable. Select Continue to swap.');setContinueReady(true);setAutoSwap(false);return}const sent=await send(fresh.data);setContinueReady(!sent);setAutoSwap(false)})()},[approve.data,approveReceipt.isSuccess]);
  useEffect(()=>{if(swapReceipt.isSuccess){void nativeBalance.refetch();void usdcBalance.refetch();void vvvBalance.refetch();void b20Balance.refetch();void allowance.refetch();void quote.refetch();void queryClient.invalidateQueries({queryKey:['latest-swaps',token]});const timer=setTimeout(()=>{swap.reset();setInput('')},1400);return()=>clearTimeout(timer)}},[allowance,b20Balance,nativeBalance,queryClient,quote,swap,swapReceipt.isSuccess,token,usdcBalance,vvvBalance]);
  const busy=simulating||autoSwap||approve.isPending||approveReceipt.isLoading||swap.isPending||swapReceipt.isLoading||swapReceipt.isSuccess;
  const routedOutputUsd=currentQuote?(asset==='USDC'?Number(formatUnits(currentQuote.output,6)):(fx.data?.prices[asset]||0)*Number(formatUnits(currentQuote.output,18))):undefined;
  const inputUsd=side==='buy'?Number(formatUnits(amountIn,assetDecimals(asset)))*(fx.data?.prices[asset]||0):routedOutputUsd;
  const outputUsd=side==='buy'?inputUsd:routedOutputUsd;
  function percentage(value:number){let usable=balance;if(side==='buy'&&asset==='ETH')usable=balance>ETH_GAS_RESERVE?balance-ETH_GAS_RESERVE:0n;setInput(formatUnits(usable*BigInt(value)/100n,balanceDecimals))}
  async function send(nextQuote=currentQuote){if(!client||!address||!nextQuote)return false;setSimulating(true);setLocalError('');const deadline=BigInt(Math.floor(Date.now()/1000)+deadlineMinutes*60);const nextMinimumVVV=applySlippage(nextQuote.vvvAmount,slippageBps);const nextMinimumOut=applySlippage(nextQuote.output,slippageBps);try{
    if(side==='buy'&&asset==='ETH'){const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactETHForB20',args:[token,nextMinimumVVV,nextMinimumOut,address,deadline],value:amountIn});await swap.writeContractAsync(request)}
    else if(side==='buy'&&asset==='USDC'){const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactUSDCForB20',args:[token,amountIn,nextMinimumVVV,nextMinimumOut,address,deadline]});await swap.writeContractAsync(request)}
    else if(side==='buy'){const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactVVVForB20',args:[token,amountIn,nextMinimumOut,address,deadline]});await swap.writeContractAsync(request)}
    else if(asset==='ETH'){const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactB20ForETH',args:[token,amountIn,nextMinimumVVV,nextMinimumOut,address,deadline]});await swap.writeContractAsync(request)}
    else if(asset==='USDC'){const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactB20ForUSDC',args:[token,amountIn,nextMinimumVVV,nextMinimumOut,address,deadline]});await swap.writeContractAsync(request)}
    else{const {request}=await client.simulateContract({account:address,address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'swapExactB20ForVVV',args:[token,amountIn,nextMinimumOut,address,deadline]});await swap.writeContractAsync(request)}
    setContinueReady(false);return true
  }catch(error){setLocalError(error instanceof Error?error.message:'Transaction simulation failed.');return false}finally{setSimulating(false)}}
  async function continueSwap(){setAutoSwap(true);const fresh=await quote.refetch();if(!fresh.data||fresh.data.amountIn!==amountIn){setLocalError('A fresh on-chain quote is unavailable. Please try again.');setAutoSwap(false);return}const sent=await send(fresh.data);setContinueReady(!sent);setAutoSwap(false)}
  const unsupported=validToken.isFetched&&!validToken.data;const error=localError||quote.error?.message||approve.error?.message||swap.error?.message;const actionLabel=!isConnected?'Connect wallet':chainId!==chain.id?'Switch to Base':unsupported?'Not a Launcher v1 token':amountIn<=0n?'Enter an amount':amountIn>balance?'Insufficient balance':autoSwap?'Opening swap transaction…':continueReady?'Continue to swap':!currentQuote?'Finding on-chain quote…':needsApproval?`Approve ${side==='sell'?symbol:asset}`:simulating?'Simulating…':`${side==='buy'?'Buy':'Sell'} ${side==='buy'?symbol:asset}`;
  const disabled=busy||unsupported||(!isConnected?true:chainId!==chain.id?false:amountIn<=0n||amountIn>balance||(!continueReady&&(!currentQuote||quote.isError)));
  function action(){if(!isConnected)return;if(chainId!==chain.id){switchChain.switchChain({chainId:chain.id});return}if(continueReady){void continueSwap();return}if(needsApproval&&approvalToken){handledApproval.current=undefined;setContinueReady(false);setLocalError('');approve.writeContract({address:approvalToken,abi:erc20Abi,functionName:'approve',args:[ADDRESSES.swapRouter,amountIn]});return}void send()}
  return <><div className="card p-5"><div className="flex rounded-xl bg-black/25 p-1">{(['buy','sell'] as const).map(value=><button key={value} disabled={busy} onClick={()=>{setSide(value);setInput('');setContinueReady(false);setLocalError('')}} className={`min-h-11 flex-1 rounded-lg font-bold capitalize disabled:cursor-wait ${side===value?'bg-white/10 text-cyan':'text-muted'}`}>{value}</button>)}</div><div className="mt-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan">B20 / VVV pool</p><h2 className="mt-1 font-display text-xl font-bold">{side==='buy'?'Buy':'Sell'} {symbol}</h2></div><select value={asset} disabled={busy} onChange={e=>{setAsset(e.target.value as RouteAsset);setInput('');setContinueReady(false)}} className="rounded-xl border border-white/10 bg-[#171421] px-3 py-2 font-bold disabled:cursor-wait"><option>ETH</option><option>USDC</option><option>VVV</option></select></div>
  {unsupported&&<p className="mt-4 rounded-xl border border-amber-400/30 bg-amber-400/10 p-3 text-sm text-amber-100">This token is not a Liqpad Launcher v1 token. Trading is disabled.</p>}
  <div className="mt-5 rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex justify-between text-xs text-muted"><span>You pay</span><span>Balance {compactToken(balance,balanceDecimals)} {side==='buy'?asset:symbol}</span></div><div className="mt-2 flex items-center gap-3"><input inputMode="decimal" value={input} disabled={busy} onChange={e=>{setInput(e.target.value.replace(/[^0-9.]/g,''));setContinueReady(false)}} placeholder="0" className="min-w-0 flex-1 bg-transparent text-3xl font-semibold outline-none"/><b>{side==='buy'?asset:symbol}</b></div><div className="mt-3 flex items-center justify-between"><strong className="text-white">{fx.isError?'USD unavailable':usd(inputUsd)}</strong><div className="flex gap-1">{[20,50,100].map(p=><button key={p} disabled={busy} onClick={()=>{percentage(p);setContinueReady(false)}} className="min-h-9 rounded-lg border border-white/10 px-2.5 text-xs font-bold text-cyan disabled:cursor-wait disabled:opacity-40">{p===100?'MAX':`${p}%`}</button>)}</div></div></div>
  <div className="relative z-10 mx-auto -my-2 grid h-11 w-11 place-items-center rounded-xl border border-white/10 bg-ink text-cyan">↓</div><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex justify-between text-xs text-muted"><span>You receive</span><span>On-chain estimate</span></div><div className="mt-2 flex items-center gap-3"><div className="min-w-0 flex-1 truncate text-3xl font-semibold">{amountIn>0n&&!currentQuote?'…':currentQuote?compactToken(currentQuote.output,side==='sell'?assetDecimals(asset):18):'0'}</div><b>{side==='buy'?symbol:asset}</b></div><strong className="mt-3 block text-lg text-white">{outputUsd==null?'USD unavailable':usd(outputUsd)}</strong></div>
  {currentQuote&&<div className="mt-4 space-y-2 rounded-xl border border-white/[.07] p-3 text-xs"><div className="flex justify-between gap-3"><span className="text-muted">Route</span><span className="text-right">{currentQuote.route.replace('B20',symbol)}</span></div><div className="flex justify-between"><span className="text-muted">Minimum received</span><span>{compactToken(minimumOut,side==='sell'?assetDecimals(asset):18)} {side==='buy'?symbol:asset}</span></div><div className="flex justify-between"><span className="text-muted">Price impact</span><span>Included in on-chain quote</span></div></div>}
  <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-muted">Slippage %<input disabled={busy} type="number" min="0.01" max="20" step="0.1" value={slippage} onChange={e=>setSlippage(Number(e.target.value))} className="input mt-1 disabled:cursor-wait"/></label><label className="text-xs text-muted">Deadline (min)<input disabled={busy} type="number" min="1" max="60" value={deadlineMinutes} onChange={e=>setDeadlineMinutes(Math.max(1,Number(e.target.value)))} className="input mt-1 disabled:cursor-wait"/></label></div>{(approve.isPending||approveReceipt.isLoading||autoSwap||continueReady)&&<div className="mt-4 rounded-xl border border-cyan/20 bg-cyan/[.06] p-3 text-xs"><div className="flex justify-between"><span className={approveReceipt.isSuccess?'text-cyan':'font-bold text-white'}>1 of 2 · Approve</span><span>{approveReceipt.isSuccess?'✓':'In progress'}</span></div><div className="mt-2 flex justify-between"><span className={autoSwap||continueReady?'font-bold text-white':'text-muted'}>2 of 2 · Swap</span><span>{autoSwap?'Opening wallet…':continueReady?'Ready':'Waiting'}</span></div></div>}{error&&amountIn>0n&&<p className="mt-3 line-clamp-3 rounded-xl border border-red-400/20 bg-red-400/[.07] p-3 text-xs text-red-200">{error}</p>}<button onClick={action} disabled={disabled} className="btn btn-primary mt-4 min-h-12 w-full disabled:opacity-40">{actionLabel}</button><p className="mt-3 text-center text-xs text-muted">Exact-input · LiqpadSwapRouter · ETH/USDC are routing assets</p></div>
  {(approve.isPending||approveReceipt.isLoading)&&<SwapTransactionOverlay kind="approval" status={approve.isPending?'wallet':'confirming'} hash={approve.data}/>} {autoSwap&&!swap.isPending&&!swap.data&&<SwapTransactionOverlay kind="swap" status="wallet"/>} {(swap.isPending||swapReceipt.isLoading||swapReceipt.isSuccess)&&<SwapTransactionOverlay kind="swap" status={swap.isPending?'wallet':swapReceipt.isLoading?'confirming':'success'} hash={swap.data}/>}</>;
}
