'use client';
import {useQuery} from '@tanstack/react-query';
import {formatUnits,type Address} from 'viem';
import {usePublicClient} from 'wagmi';
import {ADDRESSES} from '@/lib/constants';
import {usd,usdPrice} from '@/lib/swap';
import {swapRouterAbi} from '@/src/abi/swapRouter';
import {v4QuoterAbi} from '@/src/abi/swapSupport';

const SAMPLE_VVV=100_000_000_000_000_000n;
export function TokenStats({token}:{token:Address}){const client=usePublicClient();const metrics=useQuery({queryKey:['token-market',token],enabled:!!client,staleTime:30_000,retry:1,queryFn:async()=>{if(!client)throw new Error('RPC unavailable');const [key,fxResponse]=await Promise.all([client.readContract({address:ADDRESSES.swapRouter,abi:swapRouterAbi,functionName:'poolKey',args:[token]}),fetch('/api/fx')]);const fx=await fxResponse.json() as {prices:{VVV:number|null}};const zeroForOne=key.currency0.toLowerCase()===ADDRESSES.vvv.toLowerCase();const quote=await client.simulateContract({address:ADDRESSES.v4Quoter,abi:v4QuoterAbi,functionName:'quoteExactInputSingle',args:[{poolKey:key,zeroForOne,exactAmount:SAMPLE_VVV,hookData:'0x'}]});const tokenOut=Number(formatUnits(quote.result[0],18));const vvvPerToken=0.1/tokenOut;const priceUsd=fx.prices.VVV?vvvPerToken*fx.prices.VVV:null;return {vvvPerToken,priceUsd,marketCap:priceUsd?priceUsd*1_000_000_000:null}}});const cards=[{label:'Price',value:metrics.isLoading?'…':usdPrice(metrics.data?.priceUsd),detail:metrics.data?`${metrics.data.vvvPerToken.toLocaleString('en-US',{maximumSignificantDigits:4})} VVV / token`:'VVV price unavailable'},{label:'Market cap',value:metrics.isLoading?'…':usd(metrics.data?.marketCap),detail:'1B fixed supply'},{label:'FDV',value:metrics.isLoading?'…':usd(metrics.data?.marketCap),detail:'Same as market cap'},{label:'24h volume',value:'$—',detail:'Awaiting swap index'},{label:'24h traders',value:'—',detail:'Awaiting swap index'},{label:'Burned fees',value:'— B20',detail:'1% hook fee'}];return <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map(card=><div className="card min-w-0 p-4" key={card.label}><p className="text-xs text-muted">{card.label}</p><p className="mt-2 truncate text-lg font-black text-white">{card.value}</p><p className="mt-1 truncate text-[11px] text-muted" title={card.detail}>{card.detail}</p></div>)}</section>}
