'use client';

import Link from 'next/link';
import {useQuery} from '@tanstack/react-query';
import {formatToken,formatBps,reserveMismatch,subtractFloor,usdFromWei,type ProtocolEventRow,type ValueKind} from '@/lib/transparency';
import {short} from '@/lib/utils';
import {usd} from '@/lib/swap';
import {useState} from 'react';
import {Pagination} from '@/components/pagination';
import {ProtocolActions} from '@/components/protocol-actions';
import {ProtocolGrowthChart} from '@/components/protocol-growth-chart';

type Data={chainId:number;updatedAt:string;latestBlock:string|null;indexedBlock:string|null;price:{usd:number;source:string;timestamp:number}|null;diemPrice:{usd:number;source:string;timestamp:number}|null;current:Record<string,string|boolean|null>;lifetime:{protocolFees:string|null;totalSwept:string|null};events:ProtocolEventRow[];contributions:Array<{token:string;creator:string;creatorAmount:string|bigint;platformAmount:string|bigint;latestTx:string;name?:string;symbol?:string}>;addresses:Record<string,string>;warnings:Record<string,string|null>};
const scan=(address:string)=>`https://basescan.org/address/${address}`;
const txScan=(hash:string)=>`https://basescan.org/tx/${hash}`;

export function TransparencyDashboard(){
  const [contributionPage,setContributionPage]=useState(1);const [activityPage,setActivityPage]=useState(1);
  const query=useQuery<Data>({queryKey:['protocol-transparency'],queryFn:async()=>{const response=await fetch('/api/transparency');if(!response.ok)throw new Error('Transparency data request failed.');return response.json()},refetchInterval:()=>typeof document!=='undefined'&&document.hidden?false:60_000,staleTime:30_000,retry:1});
  if(query.isLoading)return <TransparencySkeleton/>;
  if(query.isError||!query.data)return <div className="mx-auto max-w-7xl px-4 py-20"><div className="card p-8"><h1 className="font-display text-3xl font-bold">Protocol Transparency</h1><p className="mt-4 text-red-300">Live data is temporarily unavailable. No balances have been replaced with zero.</p><button className="btn btn-ghost mt-6" onClick={()=>query.refetch()}>Try again</button></div></div>;
  const d=query.data,c=d.current,price=d.price?.usd??null,diemPrice=d.diemPrice?.usd??null;const contributionSize=20,activitySize=25;const contributionRows=d.contributions.slice((contributionPage-1)*contributionSize,contributionPage*contributionSize);const activityRows=d.events.slice((activityPage-1)*activitySize,activityPage*activitySize);
  const metrics=[
    ['Lifetime Protocol VVV Fees',d.lifetime.protocolFees,'lifetime','FeeRouter','Sum of indexed FeeAccrued.platformAmount.'],
    ['Pending in FeeRouter',c.platformAccrued,'pending','FeeRouter','Current FeeRouter.platformAccrued().'],
    ['VVV Received by DiemEngine',c.vvvReceived,'lifetime','DiemEngine','Lifetime DiemEngine vvvReceived() counter.'],
    ['Current Liquid VVV Reserve',c.engineVvv,'current','DiemEngine','Current VVV.balanceOf(DiemEngine).'],
    ['Lifetime VVV Staked',c.vvvStaked,'lifetime','DiemEngine','Lifetime DiemEngine vvvStaked() counter.'],
    ['sVVV Locked',c.sVVVLocked,'lifetime','DiemEngine','DiemEngine sVVVLocked() protocol counter.'],
    ['Lifetime DIEM Minted',c.diemMinted,'lifetime','DiemEngine','Lifetime DiemEngine diemMinted() counter.'],
    ['DIEM Staked',c.diemStaked,'lifetime','DiemEngine','DiemEngine diemStaked() protocol counter.'],
  ] as const;
  const warning=Object.values(d.warnings).filter(Boolean);
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:py-14">
    <section className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge tone="green">● Base Mainnet</Badge><Badge tone="blue">Live · on-chain</Badge>{query.isStale&&<Badge tone="amber">Stale</Badge>}</div><h1 className="mt-5 font-display text-4xl font-black sm:text-6xl">Protocol Transparency</h1><p className="mt-4 max-w-3xl text-lg text-muted">Follow Liqpad’s protocol fee allocation from trading activity to VVV staking, sVVV locking, and DIEM.</p></div><div className="card min-w-0 p-4 text-sm text-muted lg:w-80"><p>Last updated <span className="text-white">{new Date(d.updatedAt).toLocaleString()}</span></p><p className="mt-1">Latest indexed block <span className="font-mono text-white">{d.indexedBlock||'Unavailable'}</span></p><button onClick={()=>query.refetch()} disabled={query.isFetching} className="btn btn-ghost mt-3 w-full">{query.isFetching?'Refreshing…':'Refresh data'}</button></div></section>
    <p className="mt-6 rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm text-muted">All balances and cumulative counters are read from public Base contracts. USD values are estimates based on the latest available VVV market price. <a href="#methodology" className="text-cyan">Methodology</a> · <a href="#contracts" className="text-cyan">Verified contracts</a></p>
    {warning.length>0&&<div className="mt-4 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-100">{warning.map(x=><p key={x}>⚠ {x}</p>)}</div>}

    <section className="mt-10"><SectionTitle title="Protocol metrics" subtitle="Current balances, pending balances, and lifetime counters remain separate."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label,value,kind,source,tip])=><Metric key={label} label={label} value={value as string|null} kind={kind} source={source} address={source==='FeeRouter'?d.addresses.feeRouter:d.addresses.diemEngine} price={label.includes('DIEM')?diemPrice:price} tip={tip}/>)}</div></section>

    <section className="mt-12 grid gap-6 lg:grid-cols-2"><div className="card p-6"><SectionTitle title="Fee allocation" subtitle="Assessed trading fees—not 30% of trading volume."/><div className="mt-6 flex h-12 overflow-hidden rounded-xl text-sm font-bold"><div className="grid w-[70%] place-items-center bg-cyan/80 text-ink">70% · Creator revenue</div><div className="grid w-[30%] place-items-center bg-magenta text-white">30% · Protocol</div></div><p className="mt-5 text-sm leading-6 text-muted">The Uniswap v4 pool LP fee is zero. On VVV → B20 buys, the Hook assesses 1% of exact VVV input. On B20 → VVV sells, the Hook burns 1% of exact B20 input and assesses 1% of gross VVV output. Assessed VVV is allocated 70% to the creator and 30% to protocol-owned Venice capital. B20 fees are burned and never enter FeeRouter.</p></div><div className="card p-6"><SectionTitle title="DiemEngine status" subtitle="Live configuration and operational state."/><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Config label="Liquid reserve target" value={formatBps(c.reserveBps as string|null)}/><Config label="Minimum output" value={formatBps(c.minOutBps as string|null)}/><Config label="Minimum mint" value={`${formatToken(c.minMintSVVV as string|null)} sVVV`}/><Config label="Unwind delay" value={c.unwindDelay==null?'Unavailable':`${c.unwindDelay}s`}/><Config label="Automatic DIEM staking" value={c.autoStakeDiem==null?'Unavailable':c.autoStakeDiem?'Enabled':'Disabled'}/><Config label="Harvest" value={c.harvestPaused==null?'Unavailable':c.harvestPaused?'Paused':'Active'} tone={c.harvestPaused?'text-red-300':'text-emerald-300'}/><Config label="Unwind" value={c.unwindStarted==null?'Unavailable':c.unwindStarted?'Active':'Not active'} tone={c.unwindStarted?'text-amber-300':'text-emerald-300'}/><Config label="Owner" value={typeof c.owner==='string'?short(c.owner):'Unavailable'}/></div><p className="mt-5 text-xs leading-5 text-muted">VVV staking can begin after protocol VVV is swept to DiemEngine and harvest is called. DIEM minting occurs only when unlocked sVVV reaches the configured minimum.</p></div></section>

    <section className="mt-12"><SectionTitle title="Capital flow" subtitle="The path taken by the protocol’s 30% allocation."/><div className="grid gap-3 lg:grid-cols-7 lg:items-stretch"><Flow label="Trading" value="VVV ↔ B20"/><Arrow/><Flow label="FeeRouter" value={`${formatToken(c.platformAccrued as string|null)} VVV pending`}/><Arrow/><Flow label="DiemEngine" value={`${formatToken(c.engineVvv as string|null)} VVV liquid`}/><Arrow/><Flow label="VeniceAdapter" value={`${formatToken(c.adapterSvvv as string|null)} sVVV · ${formatToken(c.adapterDiem as string|null)} DIEM`}/></div></section>

    <ProtocolActions pending={c.platformAccrued as string|null} engineBalance={c.engineVvv as string|null} harvestPaused={c.harvestPaused as boolean|null} onComplete={async()=>{await query.refetch()}}/>

    <section className="mt-12"><SectionTitle title="Where are the funds now?" subtitle="Direct balances, protocol accruals, and derived creator reserves are labeled separately."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><State label="Creator VVV awaiting claims" value={subtractFloor(c.feeRouterVvv as string|null,c.platformAccrued as string|null)} token="VVV" note="Derived from FeeRouter balance minus protocol VVV pending sweep."/><State label="Protocol VVV pending sweep" value={c.platformAccrued} token="VVV" note="Only this amount is eligible for sweepPlatform()."/><State label="VVV held by DiemEngine" value={c.engineVvv} token="VVV"/><State label="VVV held by VeniceAdapter" value={c.adapterVvv} token="VVV"/><State label="sVVV held by VeniceAdapter" value={c.adapterSvvv} token="sVVV"/><State label="Unlocked sVVV" value={subtractFloor(c.adapterSvvv as string|null,c.sVVVLocked as string|null)} token="sVVV" note="Derived from adapter sVVV balance minus DiemEngine sVVV locked."/><State label="DIEM held by VeniceAdapter" value={c.adapterDiem} token="DIEM"/><State label="DIEM recorded as staked" value={c.diemStaked} token="DIEM"/><State label="DIEM recorded as liquid" value={c.diemLiquid} token="DIEM"/></div>{reserveMismatch(c.engineVvv as string|null,c.accountedLiquidVVV as string|null)&&<p className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">The current DiemEngine VVV balance differs from accountedLiquidVVV(). Review direct transfers or pending accounting transitions.</p>}</section>

    <ProtocolGrowthChart/>

    <section className="mt-12"><SectionTitle title="Per-token contribution" subtitle="Aggregated from FeeAccrued events."/><div className="card overflow-x-auto">{d.contributions.length?<table className="w-full min-w-[850px] text-left text-sm"><thead className="text-muted"><tr>{['Token','Creator','Total assessed','Creator 70%','Protocol 30%','Share','Latest tx'].map(h=><th key={h} className="px-4 py-4">{h}</th>)}</tr></thead><tbody>{contributionRows.map(row=>{const total=BigInt(row.creatorAmount)+BigInt(row.platformAmount);const all=BigInt(d.lifetime.protocolFees||0);return <tr key={row.token} className="border-t border-white/10"><td className="px-4 py-4"><Link href={`/token/${row.token}`} className="font-bold text-cyan">{row.symbol||short(row.token)}</Link></td><td className="px-4 font-mono">{short(row.creator)}</td><td className="px-4">{formatToken(total)} VVV</td><td className="px-4">{formatToken(row.creatorAmount)} VVV</td><td className="px-4">{formatToken(row.platformAmount)} VVV</td><td className="px-4">{all>0n?`${Number(BigInt(row.platformAmount)*10000n/all)/100}%`:'—'}</td><td className="px-4"><a href={txScan(row.latestTx)} target="_blank" rel="noreferrer" className="text-cyan">{short(row.latestTx)} ↗</a></td></tr>})}</tbody></table>:<Empty/>}</div><Pagination page={contributionPage} totalPages={Math.max(1,Math.ceil(d.contributions.length/contributionSize))} totalItems={d.contributions.length} pageSize={contributionSize} onPageChange={setContributionPage} label="tokens"/></section>

    <section className="mt-12"><SectionTitle title="Recent protocol activity" subtitle="Confirmed Base events, newest first."/><div className="card overflow-x-auto">{d.events.length?<table className="w-full min-w-[820px] text-left text-sm"><thead className="text-muted"><tr>{['Activity','Token','Amount','Block','Time','Transaction'].map(h=><th key={h} className="px-4 py-4">{h}</th>)}</tr></thead><tbody>{activityRows.map(event=><Activity key={event.id} event={event}/>)}</tbody></table>:<Empty/>}</div><Pagination page={activityPage} totalPages={Math.max(1,Math.ceil(d.events.length/activitySize))} totalItems={d.events.length} pageSize={activitySize} onPageChange={setActivityPage} label="events"/></section>

    <section id="methodology" className="mt-12 scroll-mt-24"><SectionTitle title="Methodology and disclosures" subtitle="How to interpret this dashboard."/><div className="card space-y-4 p-6 text-sm leading-6 text-muted"><p><b className="text-white">Volume versus fees.</b> Liqpad does not receive 30% of trading volume. The Hook assesses fees under the rules above; FeeRouter allocates collected VVV 70% to creators and 30% to protocol-owned Venice capital.</p><p><b className="text-white">Pending and lifetime.</b> Pending FeeRouter VVV and current ERC-20 balances are point-in-time assets. FeeAccrued totals, VVV received/staked, and DIEM minted/staked are cumulative counters and are never added together as treasury assets.</p><p><b className="text-white">Capital operations.</b> sweepPlatform() and harvest() are permissionless. DiemEngine maintains a configured liquid reserve, stakes VVV through VeniceAdapter, locks sVVV, mints DIEM after the threshold, and may stake DIEM when enabled. Timelocked unwind status is displayed whenever active.</p><p><b className="text-white">sVVV proxy.</b> The canonical sVVV address is an ERC-1967 proxy. Balances are read from the proxy at 0x321b7…340Ff; the verified implementation is linked separately and is not treated as the token balance address.</p><p><b className="text-white">Prices.</b> VVV uses the existing CoinGecko/DefiLlama resolver. DIEM/USD is fetched server-side from GeckoTerminal’s public Base token-price endpoint and cached for 30 seconds.</p><p><b className="text-white">Operational separation.</b> Quote-signer operations authorize launch pricing and are unrelated to protocol treasury custody. External Venice, token, Base RPC, indexer, and market-price dependencies may be delayed or unavailable.</p><p>USD values are informational estimates. Token balances and protocol counters come from Base. External market prices may be delayed or unavailable. BaseScan source verification does not itself prove the correctness of frontend calculations.</p></div></section>

    <section id="contracts" className="mt-12 scroll-mt-24"><SectionTitle title="Verified contracts" subtitle="Canonical Liqpad Launcher v1 addresses on Base Mainnet."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(d.addresses).map(([name,address])=><a key={name} href={scan(address)} target="_blank" rel="noreferrer" className="card min-w-0 p-4 hover:border-cyan/40"><p className="text-xs uppercase tracking-wider text-muted">{name}</p><p className="mt-2 truncate font-mono text-sm text-cyan">{address}</p></a>)}</div></section>
  </div>
}

export function TransparencySkeleton(){return <div role="status" aria-label="Loading protocol transparency" className="mx-auto max-w-7xl animate-pulse px-4 py-14 motion-reduce:animate-none"><div className="h-12 w-2/3 rounded-xl bg-white/10"/><div className="mt-5 h-6 w-1/2 rounded bg-white/5"/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="card h-36 bg-white/[.03]"/>)}</div><span className="sr-only">Loading protocol transparency…</span></div>}
function Badge({children,tone}:{children:React.ReactNode;tone:'green'|'blue'|'amber'}){const color=tone==='green'?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':tone==='amber'?'border-amber-400/30 bg-amber-400/10 text-amber-200':'border-cyan/30 bg-cyan/10 text-cyan';return <span className={`rounded-full border px-3 py-1 text-xs font-bold ${color}`}>{children}</span>}
function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="mb-5"><h2 className="font-display text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-1 text-sm text-muted">{subtitle}</p></div>}
function Metric({label,value,kind,source,address,price,tip}:{label:string;value:string|null;kind:ValueKind;source:string;address:string;price:number|null;tip:string}){const kinds={current:'Current balance',pending:'Pending balance',lifetime:'Lifetime cumulative'};return <article title={tip} className="card flex min-h-40 flex-col p-5"><p className="text-xs uppercase tracking-wider text-muted">{label}</p><p className="mt-3 text-2xl font-black">{formatToken(value)} <span className="text-sm text-muted">{label.includes('DIEM')?'DIEM':label.startsWith('sVVV')?'sVVV':'VVV'}</span></p><p className="mt-1 text-sm text-muted">{usd(usdFromWei(value,price))}</p><div className="mt-auto flex items-end justify-between gap-2 pt-4"><span className="text-[10px] font-bold uppercase tracking-wider text-cyan">{kinds[kind]}</span><a href={scan(address)} target="_blank" rel="noreferrer" className="text-xs text-muted hover:text-white">{source} ↗</a></div></article>}
function Config({label,value,tone='text-white'}:{label:string;value:string;tone?:string}){return <div className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs text-muted">{label}</p><p className={`mt-1 break-words font-bold ${tone}`}>{value}</p></div>}
function Flow({label,value}:{label:string;value:string}){return <div className="card flex min-h-28 flex-col justify-center p-4 text-center"><b>{label}</b><span className="mt-2 text-xs text-cyan">{value}</span></div>}
function Arrow(){return <div aria-hidden className="grid place-items-center text-2xl text-magenta"><span className="lg:hidden">↓</span><span className="hidden lg:inline">→</span></div>}
function State({label,value,token,note}:{label:string;value:string|boolean|null;token:string;note?:string}){return <div className="card p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-xl font-bold">{typeof value==='string'?formatToken(value):'Unavailable'} {typeof value==='string'&&<span className="text-sm text-muted">{token}</span>}</p>{note&&<p className="mt-2 text-xs leading-5 text-muted">{note}</p>}</div>}
function Empty(){return <div className="p-10 text-center text-muted">No protocol activity has been recorded for this category yet.</div>}
function Activity({event}:{event:ProtocolEventRow}){const labels:Record<string,string>={FeeAccrued:'Protocol fee accrued',PlatformSwept:'VVV swept to DiemEngine',Harvest:'VVV harvested and staked',UnwindBegun:'Unwind initiated',UnwindProgressed:'Unwind progressed',HarvestPausedSet:event.data.paused?'Harvest paused':'Harvest resumed'};const amount=event.amount_vvv?`${formatToken(event.amount_vvv)} VVV`:event.amount_diem?`${formatToken(event.amount_diem)} DIEM`:'—';return <tr className="border-t border-white/10"><td className="px-4 py-4 font-medium">{labels[event.event_name]||event.event_name}</td><td className="px-4 font-mono">{event.token?short(event.token):'—'}</td><td className="px-4">{amount}</td><td className="px-4 font-mono">{event.block_number}</td><td className="px-4 text-muted">{event.block_timestamp?new Date(event.block_timestamp).toLocaleString():'Unavailable'}</td><td className="px-4"><a href={txScan(event.tx_hash)} target="_blank" rel="noreferrer" className="text-cyan">{short(event.tx_hash)} ↗</a></td></tr>}
