import {formatUnits} from 'viem';

export type ValueKind='current'|'pending'|'lifetime';
export type ProtocolEventRow={id:string;event_name:string;contract_address:string;token:string|null;creator:string|null;amount_vvv:string|null;amount_diem:string|null;data:Record<string,string|boolean|number>;tx_hash:string;log_index:number;block_number:string;block_timestamp:string|null};

export function formatBps(value:bigint|string|null){if(value==null)return 'Unavailable';const n=BigInt(value);const whole=n/100n;const fraction=n%100n;return fraction===0n?`${whole}%`:`${whole}.${fraction.toString().padStart(2,'0').replace(/0+$/,'')}%`}
export function formatToken(value:bigint|string|null,decimals=18){if(value==null)return 'Unavailable';const raw=typeof value==='bigint'?value:BigInt(value);const number=Number(formatUnits(raw,decimals));if(!Number.isFinite(number))return 'Unavailable';if(number===0)return '0';if(number>=1e9)return `${(number/1e9).toFixed(2)}B`;if(number>=1e6)return `${(number/1e6).toFixed(2)}M`;if(number>=1e3)return `${(number/1e3).toFixed(2)}K`;return number.toLocaleString('en-US',{maximumFractionDigits:6})}
export function sumField(rows:ProtocolEventRow[],field:'amount_vvv'|'amount_diem'){return rows.reduce((total,row)=>total+BigInt(row[field]||0),0n)}
export function tokenContributions(rows:ProtocolEventRow[]){const map=new Map<string,{token:string;creator:string;creatorAmount:bigint;platformAmount:bigint;latestTx:string}>();for(const row of rows.filter(x=>x.event_name==='FeeAccrued'&&x.token)){const key=row.token!.toLowerCase();const old=map.get(key)||{token:row.token!,creator:row.creator||'',creatorAmount:0n,platformAmount:0n,latestTx:row.tx_hash};old.creatorAmount+=BigInt(String(row.data.creatorAmount||0));old.platformAmount+=BigInt(String(row.data.platformAmount||row.amount_vvv||0));if(!map.has(key))old.latestTx=row.tx_hash;map.set(key,old)}return [...map.values()].sort((a,b)=>a.platformAmount===b.platformAmount?0:a.platformAmount>b.platformAmount?-1:1)}
export function usdFromWei(value:bigint|string|null,price:number|null){if(value==null||price==null||!Number.isFinite(price)||price<=0)return null;const raw=typeof value==='bigint'?value:BigInt(value);const integer=raw/10n**18n;const remainder=raw%10n**18n;return Number(integer)*price+Number(remainder/10n**10n)/1e8*price}
export function reserveMismatch(balance:bigint|string|null,accounted:bigint|string|null){if(balance==null||accounted==null)return false;const a=typeof balance==='bigint'?balance:BigInt(balance);const b=typeof accounted==='bigint'?accounted:BigInt(accounted);const diff=a>b?a-b:b-a;return diff>1000000000000n}
export function subtractFloor(value:bigint|string|null,minus:bigint|string|null){if(value==null||minus==null)return null;const result=BigInt(value)-BigInt(minus);return (result>0n?result:0n).toString()}
