import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {supabaseAdmin} from '@/lib/supabase';
import {pageMetadata} from '@/lib/seo';

export const metadata:Metadata=pageMetadata({title:'AI Agents',description:'Discover autonomous agents and agent-owned B20 economies launched through Liqpad on Base.',path:'/agents'});
export const revalidate=30;
export default async function Page(){const db=supabaseAdmin();const {data}=db?await db.from('agents').select('slug,name,symbol,avatar_url,description,status,vitality,token_address').neq('status','draft').order('created_at',{ascending:false}).limit(48):{data:null};return <div className="mx-auto max-w-7xl px-4 py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan">Autonomous economies</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Agents on Liqpad</h1></div><Link href="/agents/create" className="btn btn-primary">Create an agent</Link></div>{data?.length?<div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.map(agent=><Link href={`/agent/${agent.slug}`} key={agent.slug} className="card p-5 transition hover:-translate-y-1 hover:border-cyan/30"><div className="flex items-center gap-4">{agent.avatar_url?<Image src={agent.avatar_url} alt="" width={56} height={56} className="h-14 w-14 rounded-2xl object-cover" unoptimized/>:<div className="grid h-14 w-14 place-items-center rounded-2xl bg-cyan/10 text-cyan">AI</div>}<div className="min-w-0"><h2 className="truncate text-xl font-black">{agent.name}</h2><p className="text-sm text-cyan">${agent.symbol}</p></div></div><p className="mt-4 line-clamp-3 text-sm text-muted">{agent.description}</p><div className="mt-5 flex justify-between text-xs"><span className="rounded-full border border-white/10 px-2 py-1">{agent.vitality}</span><span className="text-muted">{agent.token_address?'Token live':'Preparing launch'}</span></div></Link>)}</div>:<div className="card mt-10 p-10 text-center"><p className="text-2xl font-black">The agent market is quiet—for now.</p><p className="mt-2 text-muted">The first registered agent will appear here.</p></div>}</div>}
