/* eslint-disable @next/next/no-img-element */
import {ImageResponse} from 'next/og';
import {getLaunchByAddress} from '@/lib/data';
import {toGatewayUrl} from '@/lib/ipfs';
import {compactToken,usd,usdPrice} from '@/lib/swap';
import {shortB20} from '@/lib/utils';

export const runtime='edge';
export async function GET(_:Request,{params}:{params:Promise<{address:string}>}){
  const {address}=await params;const launch=await getLaunchByAddress(address);const logo=launch?.image?toGatewayUrl(launch.image):'';let burned='Indexing';try{if(launch?.burnedB20)burned=`${compactToken(BigInt(launch.burnedB20))} ${launch.symbol} burned`}catch{/* retain fallback */}
  const symbol=launch?.symbol||'B20',change=launch?.change24h;
  return new ImageResponse(<div style={{width:'100%',height:'100%',display:'flex',position:'relative',overflow:'hidden',padding:'58px 68px',color:'white',background:'#080712',fontFamily:'monospace'}}><div style={{position:'absolute',width:500,height:500,borderRadius:999,background:'rgba(255,58,167,.18)',filter:'blur(60px)',right:-120,top:-230}}/><div style={{position:'absolute',width:360,height:360,borderRadius:999,background:'rgba(64,232,255,.14)',filter:'blur(55px)',left:-150,bottom:-190}}/><div style={{display:'flex',width:'100%',flexDirection:'column'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><span style={{fontSize:25,color:'#40e8ff',letterSpacing:6}}>LIQPAD · BASE</span><div style={{display:'flex',gap:10}}><span style={{padding:'8px 14px',border:'1px solid rgba(64,232,255,.35)',borderRadius:999,fontSize:16,color:'#40e8ff'}}>◆ LP LOCKED</span><span style={{padding:'8px 14px',border:'1px solid rgba(255,255,255,.15)',borderRadius:999,fontSize:16}}>B20 · VVV</span></div></div><div style={{display:'flex',alignItems:'center',marginTop:42}}>{logo?<img src={logo} alt="" width="142" height="142" style={{width:142,height:142,borderRadius:32,objectFit:'cover'}}/>:<div style={{width:142,height:142,borderRadius:32,display:'flex',alignItems:'center',justifyContent:'center',fontSize:62,fontWeight:800,background:'linear-gradient(135deg,#ff3aa7,#40e8ff)'}}>{symbol[0]||'L'}</div>}<div style={{display:'flex',minWidth:0,flexDirection:'column',marginLeft:34}}><div style={{fontSize:62,fontWeight:900,lineHeight:1.05}}>{launch?.name||'Token profile indexing'}</div><div style={{display:'flex',marginTop:13,fontSize:27,color:'#aca4bc'}}>${symbol} · {shortB20(address)}</div></div></div><div style={{display:'flex',gap:24,marginTop:42}}><Metric label="PRICE" value={usdPrice(launch?.priceUsd)}/><Metric label="MARKET CAP" value={usd(launch?.marketCapUsd)}/><Metric label="24H VOLUME" value={usd(launch?.volume24hUsd)}/><Metric label="24H CHANGE" value={change==null?'—':`${change>=0?'+':''}${change.toFixed(2)}%`} accent={change==null?undefined:change>=0?'#63f5b2':'#ff879a'}/></div><div style={{display:'flex',marginTop:30,alignItems:'center',justifyContent:'space-between',fontSize:18}}><span style={{color:'#ffad61'}}>🔥 {burned}</span><span style={{color:'#aca4bc'}}>liqpad.com/token/{shortB20(address)}</span></div></div></div>,{width:1200,height:630,headers:{'Cache-Control':'public, max-age=60, s-maxage=300, stale-while-revalidate=3600'}});
}

function Metric({label,value,accent}:{label:string;value:string;accent?:string}){return <div style={{display:'flex',flex:1,flexDirection:'column',padding:'17px 18px',border:'1px solid rgba(255,255,255,.12)',borderRadius:18,background:'rgba(255,255,255,.035)'}}><span style={{fontSize:14,color:'#aca4bc',letterSpacing:1.4}}>{label}</span><span style={{marginTop:9,fontSize:25,fontWeight:800,color:accent||'white'}}>{value}</span></div>}
